---
engine_version: 0.4.22
file_version: 2023-11-10 20:06:55.042566000 Z
resources:
- name: task
  preferences: {}
  updated_at: 2023-11-06 05:06:11.244349000 +00:00
- name: user
  preferences: {}
  updated_at: 2023-11-06 05:06:09.135398000 +00:00
configs:
- key: header.links
  value:
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  - conditions: []
    type: header
    name: Home
    path: "/home"
    link_type: header
  updated_at: 2023-11-10 20:06:55.042566000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2023-11-05 02:35:33.795155000 +00:00
