---
engine_version: 0.4.22
file_version: 2023-11-17 19:17:43.794831000 Z
resources:
- name: task
  preferences: {}
  updated_at: 2023-11-06 05:06:11.244349000 +00:00
- name: user
  preferences: {}
  updated_at: 2023-11-06 05:06:09.135398000 +00:00
configs:
- key: header.links
  value:
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  - conditions: []
    type: header
    name: Home
    path: "/home"
    link_type: header
  updated_at: 2023-11-10 20:06:55.042566000 +00:00
queries: []
dashboards: []
forms:
- id: 1
  name: Create User
  http_method: POST
  api_path: "/users"
  description: 'Creates new users '
  preferences:
    fields:
    - display_name: User NetID
      name: user_netid
      field_type: input
      default_value: ''
      validators: []
    - display_name: Username
      name: user_name
      field_type: input
      default_value: ''
      validators: []
    - display_name: User Email
      name: user_email
      field_type: input
      default_value: ''
      validators: []
      is_array: false
    - display_name: User Level
      name: user_level
      field_type: input
      default_value: admin
      validators: []
    request_type: rest
  api_config_name: https://phdappreview-2530b5efb143.herokuapp.com
  tags:
  - "#createuser"
  updated_at: 2023-11-17 19:17:43.794831000 +00:00
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2023-11-05 02:35:33.795155000 +00:00
- id: 2
  name: PhdApplicationReview
  url: https://phdappreview-2530b5efb143.herokuapp.com
  preferences: {}
  description:
  updated_at: 2023-11-17 19:07:48.206924000 +00:00
